markdown: kramdown
pygments: false
permalink: none
exclude: ["en-US/images/precompressed/", "node_modules", "Gruntfile.js", "package.json"]
url: http://silnrsi.github.io/FDBP
baseurl: /FDBP
repourl: //github.com/silnrsi/FDBP
title: Font Development Best Practice
subtitle: A book about how to create great fonts
