markdown: kramdown
highlighter: null
permalink: none
exclude: ["en-US/images/precompressed/", "node_modules", "Gruntfile.js", "package.json"]
url: http://silnrsi.github.io/FDBP
baseurl: /FDBP
repourl: //github.com/silnrsi/FDBP
title: Font Development Best Practices
subtitle: Technical guidance regarding font development and production
